name: Update MongoDB - Fauna

on:
  push:
    branches: ['main']
    paths:
      [
        'packages/ingest/src/lib/**',
        'packages/ingest/src/fauna.ts',
        'packages/transform/src/**',
        '.github/workflows/update-mongodb-fauna.yml'
      ]
  workflow_dispatch:
    inputs:
      DWCA_URL:
        description: 'Custom DWCA URL (optional)'
        required: false
        type: string
  schedule:
    - cron: '30 2 * * 0'

env:
  DWCA_URL: https://ipt.jbrj.gov.br/jbrj/archive.do?r=catalogo_taxonomico_da_fauna_do_brasil

jobs:
  ingest-and-transform:
    permissions:
      contents: 'read'
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.21
      - name: Install zip
        run: sudo apt update && sudo apt install zip
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Ingest and Transform Fauna from custom URL
        if: ${{ github.event.inputs.DWCA_URL }}
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          TEMPDIR: /home/runner/work/Biodiversidade-Online/
        run: bun run ingest:fauna "${{ github.event.inputs.DWCA_URL }}"
      - name: Ingest and Transform Fauna
        if: ${{ !github.event.inputs.DWCA_URL }}
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          TEMPDIR: /home/runner/work/Biodiversidade-Online/
        run: bun run ingest:fauna "${{ env.DWCA_URL }}"
